name: Build and Push Docker Image

# Trigger the workflow on push to main branch
on:
  push:
    branches:
      - main  # You can change this to your branch name if it's different

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use an Ubuntu VM for this job

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Reference the secret for Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}   # Docker Hub Password stored as a secret

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and push the Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Set the context to the repository root
          file: ./Dockerfile  # Path to your Dockerfile
          push: true  # Push the image to Docker Hub
          tags: ${{ secrets.hiteshmechlin }}/timetracker:tagone  # Tag for Docker image

